# Generated by Django 2.0.3 on 2018-04-07 19:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0011_post_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tokens',
            field=django_mysql.models.SetTextField(models.CharField(max_length=255), null=True, size=None),
        ),
    ]
