# Generated by Django 2.0.3 on 2018-04-08 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_conversation', '0012_topic_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='post_upvoters', to=settings.AUTH_USER_MODEL, verbose_name='Upvoters'),
        ),
    ]
