# Generated by Django 2.0.3 on 2018-04-08 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_conversation', '0014_post_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flaggers',
            field=models.ManyToManyField(blank=True, related_name='post_flaggers', to=settings.AUTH_USER_MODEL, verbose_name='Flaggers'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Flag count'),
        ),
    ]
