# Generated by Django 2.0.3 on 2018-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0015_auto_20180408_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flag_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Flag count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vote_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Vote count'),
        ),
    ]
